development:
  adapter: postgresql
  encoding: unicode
  database: change_me_development
  host: localhost
  pool: 5
  username: dylanoshea
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: change_me_test
  host: localhost
  pool: 5
  username: dylanoshea
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: change_me_production
  host: localhost
  pool: 5
  username: dylanoshea
  password:
