development:
  adapter: postgresql
  encoding: unicode
  database: rail_jumper_4_development
  host: localhost
  pool: 5
  username: dylanoshea
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rail_jumper_4_test
  host: localhost
  pool: 5
  username: dylanoshea
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: rail_jumper_4_production
  host: localhost
  pool: 5
  username: dylanoshea
  password:
